version: 0.2
phases:
  pre_build:
    commands:
      - chmod +x ./scripts/*
      - echo Generating config
      - sh ./scripts/config_generator.sh


  build:
    commands:
      - aws ecr get-login-password --region $REGISTRY_REGION | docker login --username AWS --password-stdin $REGISTRY_URL
      - echo "Building Docker image..."

      - commit_id=$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c 1-7)
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION

      # - TAG="${REPOSITORY_URL}:${commit_id}"
      - TAG_LATEST="718460152067.dkr.ecr.eu-central-1.amazonaws.com/commercial/dre/dre-backend:latest"

      - DOCKER_FILE_PATH=${DOCKER_FILE_PATH:-dockerfile}
      
      - docker build --build-arg NODE_ENV=${ENV} -t $TAG_LATEST .
      # - docker push $TAG
      - docker push $TAG_LATEST
artifacts:
  files:
    - 'scripts/**/*' 
    - 'config/${ENV}.json'

