#!/bin/bash

echo $CONFIG_FILE
echo $PWD
cat <<EOT >> $CONFIG_FILE
# Server
APP_PORT=$APP_PORT
APP_HOST=$APP_HOST
APP_ENV=$APP_ENV
APP_PREFIX=$APP_PREFIX
APP_VERSION_PREFIX=$APP_VERSION_PREFIX
APP_CORS_ORIGINS=$APP_CORS_ORIGINS

# Database
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME

# JWT
JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
JWT_ACCESS_EXPIRES_IN=$JWT_ACCESS_EXPIRES_IN

# Redis
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT
# REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_TTL_SECONDS=$REDIS_TTL_SECONDS

# AWS
AWS_REGION=$AWS_REGION
AWS_S3_BUCKET=$AWS_S3_BUCKET
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

# I18n
I18N_FALLBACK_LANG=$I18N_FALLBACK_LANG

# Swagger
SWAGGER_TITLE=$SWAGGER_TITLE
SWAGGER_DESCRIPTION=$SWAGGER_DESCRIPTION
SWAGGER_VERSION=$SWAGGER_VERSION
SWAGGER_APPHOST=$SWAGGER_APPHOST
EOT
